# Generated by Django 5.0.6 on 2024-07-11 08:19

import record.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("record", "0001_initial")]

    operations = [migrations.AlterField(model_name="accident", name="accident_video", field=models.FileField(upload_to=record.models.upload_to))]
